import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const geistSans = localFont({
  src: [
    {
      path: '../public/otf/Geist-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/otf/Geist-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/otf/Geist-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/otf/Geist-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/otf/Geist-SemiBold.otf',
      weight: '600',
      style: 'normal',
    }
  ],
  variable: '--font-geist-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
